version: "3"

services:
  redis:
    image: redis
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    build: .
    environment:
      BASE_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
      SPOTIFY_CLIENT_ID: $SPOTIFY_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
    ports:
      - 3000:3000

volumes:
  redis-data:
