version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  app:
    build: .
    environment:
      BASE_URL: http://localhost:3000
      REDIS_URL: redis://redis:6379
      SPOTIFY_CLIENT_ID: $SPOTIFY_CLIENT_ID
      SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
    ports:
      - 3000:3000
